### ISSUE TITLE
Will this work offline? What models are you using?

### ISSUE THREAD

**Issue by jifalops** [Flutter-Bounty-Hunters/nlp#7]
Hi I've been looking for something similar to this and am considering using `spaCy` but it requires a python runtime baked into apps. Will this library work offline? How does it work under the hood?

**Comment by drxddy** [comment]
it could work offline since it is logic-based (symbolic system), but there is also python interop available in flutter, in dartpy, serious_python, flython are some plugins to run python in flutter apps, maybe it could work for you using `spaCy`

**Comment by matthew-carroll** [comment]
I assume by "models" you mean ML models? If so, this package doesn't use any ML. It's all based on regex - adapted from a .NET project.

Yes it will work offline because the regex is compiled into the package.

We don't currently have a timeline for release.
